version: '3.9'

services:
  lio2_container:
    image: liosam-color  # 여기에 사용할 이미지 이름을 지정하세요
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /home/${USER}/navifra_source_repository/:/root/workspace/
      - /home/${USER}/.ros/:/root/.ros
    network_mode: host
    shm_size: 12G
    stdin_open: true
    tty: true
